name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      
      - name: Setup ⚙
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          
      - name: Install ⬇
        run: npm install

      - name: Test 🧪
        run: npm test

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
